name: Cross-Compile App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-linux-android

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --locked

      # Optional: ensure correct Android SDK setup
      - name: Install Android NDK
        if: matrix.target == 'aarch64-linux-android'
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip -q android-ndk-r27c-linux.zip -d $HOME
          echo "NDK_HOME=$HOME/android-ndk-r27c" >> $GITHUB_ENV
          echo "$HOME/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Build with cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: leech-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/leech
